name: raseed_agent_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Core
  firebase_core: ^2.27.0
  # Firebase Authentication
  firebase_auth: ^4.17.8
  # Firestore Database
  cloud_firestore: ^4.15.8
  # Firebase Cloud Functions
  cloud_functions: ^4.6.8
  
  # State Management (Riverpod is modern and powerful)
  flutter_riverpod: ^2.5.1

  # For Google Sign-In
  google_sign_in: ^6.2.1
  
  # For formatting dates
  intl: ^0.19.0
  http:


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/